version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "dockerfile.web"
    env_file: .env
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
  worker:
    build:
      context: .
      dockerfile: "dockerfile.worker"
    env_file: .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: almafa1
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
