version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "dockerfile.web"
    env_file: .env
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: "dockerfile.worker"
    env_file: .env
    environment:
      HOST: "0.0.0.0"
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
