version: '3'
services:
  web:
    image: frenetiq/caolo-web
    env_file: docker.env
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres

    entrypoint:
      - python
      - app.py

  worker:
    image: frenetiq/caolo-worker
    env_file: docker.env
    depends_on:
      - redis
      - postgres
    entrypoint:
      - /caolo

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: almafa1
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
