version: "3.7"
services:
  release:
    build: 
      context: .
      dockerfile: ./dockerfile.release
    image: frenetiq/caolo-release:bleeding
    env_file: docker.env
    depends_on:
      - postgres
  web:
    build: 
      context: .
      dockerfile: ./dockerfile.web
    image: frenetiq/caolo-web:bleeding
    env_file: docker.env
    environment:
      HOST: 0.0.0.0
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - cache
      - postgres

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      timeout: 1s
      retries: 3
      start_period: 5s

  worker:
    build: 
      context: .
      dockerfile: ./dockerfile.worker
    image: frenetiq/caolo-worker:bleeding
    env_file: docker.env
    depends_on:
      - cache
      - postgres

  cache:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  db-data:
    driver: local
