apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: caolo/caolo-release
      context: .
      docker:
        dockerfile: release.Dockerfile
    - image: caolo/caolo-api
      context: .
      docker:
        dockerfile: api.Dockerfile
    - image: caolo/caolo-rt
      context: .
      docker:
        dockerfile: rt.Dockerfile
    - image: caolo/caolo-sim
      context: .
      docker:
        dockerfile: sim.Dockerfile
test:
  - image: caolo/caolo-sim
    custom:
      - command: cargo test --benches --all
        dependencies:
          paths:
            - "sim/**/*.rs"
      - command: cargo test --doc
        dependencies:
          paths:
            - "sim/**/*.rs"
