apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: caolo-backend
build:
  local:
    tryImportMissing: true
    concurrency: 0
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: caolo/caolo-sim
      docker:
        dockerfile: sim.Dockerfile
    - image: caolo/caolo-api
      docker:
        dockerfile: api.Dockerfile
    - image: caolo/caolo-release
      docker:
        dockerfile: release.Dockerfile
    - image: caolo/caolo-rt
      docker:
        dockerfile: rt.Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/db.yml
      - k8s/queen.yml
      - k8s/rt.yml
      - k8s/web.yml
