apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: caolo/caolo-sim
      context: .
      docker:
        dockerfile: sim.Dockerfile
    - image: caolo/caolo-release
      context: .
      docker:
        dockerfile: release.Dockerfile
    - image: caolo/caolo-api
      context: .
      docker:
        dockerfile: api.Dockerfile
    - image: caolo/caolo-rt
      context: .
      docker:
        dockerfile: rt.Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*
