version: 2

jobs:
  test_worker:
    docker:
      - image: rust:1.40.0

    steps:
      - checkout
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check
          command: cargo check
      - run:
          name: Test
          command: cargo test
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

workflows:
  version: 2
  build_test:
    jobs:
      - test_worker
