version: 2

jobs:
  test_worker:
    docker:
      - image: rust:1.40.0

    steps:
      - checkout
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Update submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Install protoc
          command: |
            curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/protoc-3.11.3-linux-x86_64.zip
            unzip -o  protoc-3.11.3-linux-x86_64.zip -d /usr/local bin/protoc
      - run:
          name: Check
          command: cargo check
      - run:
          name: Test
          command: cargo test --all-features --benches
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

workflows:
  version: 2
  build_test:
    jobs:
      - test_worker
