version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Run Tilt
          command: |
            ctlptl create cluster kind --registry=ctlptl-registry
            tilt ci
            tilt down
