apiVersion: apps/v1
kind: Deployment
metadata:
  name: caolo-rt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caolo-rt
  template:
    metadata:
      labels:
        app: caolo-rt
    spec:
      restartPolicy: Always
      containers:
        - name: caolo-rt
          image: caolo/caolo-rt
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: PORT
              value: "8080"
            - name: CAO_QUEEN_TAG
              value: boises
            - name: CAO_QUEEN_URL
              value: caolo-queen:50051

---
apiVersion: v1
kind: Service
metadata:
  name: caolo-rt
spec:
  type: LoadBalancer
  ports:
    - name: "caolo-rt"
      port: 8080
  selector:
    app: caolo-rt
