apiVersion: apps/v1
kind: Deployment
metadata:
  name: caolo-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caolo-web
  template:
    metadata:
      labels:
        app: caolo-web
    spec:
      initContainers:
        - name: web-release
          image: caolo/caolo-release
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - /caolo/release.sh
          env:
            - name: DATABASE_URL
              value: postgres://postgres:poggers@postgresql:5432?sslmode=disable

      restartPolicy: Always
      containers:
        - name: caolo-web
          image: caolo/caolo-api
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: WEB_CONCURRENCY
              value: "2"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: postgres://postgres:poggers@postgresql:5432?sslmode=disable
            - name: CAO_QUEEN_TAG
              value: boises
            - name: CAO_QUEEN_URL
              value: caolo-queen:50051

---
apiVersion: v1
kind: Service
metadata:
  name: caolo-web
spec:
  type: LoadBalancer
  ports:
    - name: "caolo-web"
      port: 8000
  selector:
    app: caolo-web
