[package]
name = "caolo-worker"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "*"
actix-web = "1.0"
actix-web-actors = "*"

caolo-engine = { path = "../engine", features=["inmemory_storage", "profile"] }
caolo-api = { path = "../api" }
log = "*"
env_logger = "0.6"
dotenv = "0.14"
chrono = { version="0.4", features=["serde"] }
serde_json = "*"
serde = "*"
serde_derive = "*"
rand = "*"
