[package]
name = "caolo-worker"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["dotenv"]
dotenv = ["dep-dotenv"]

[dependencies]
caolo-sim = { path = "../simulation", features=[] }
caolo-api = { path = "../api" }
cao-lang = { path = "../cao-lang" }
log = "*"
env_logger = "*"
chrono = { version="0.4", features=["serde"] }
serde_json = "1"
serde = "1"
serde_derive = "1"
redis = "0.15"
rand="*"

dep-dotenv = { version="0.14", optional=true, package="dotenv" }
uuid = { version="0.7" }
