[package]
name = "caolo-worker"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"

[[bin]]
name = "caolo-worker"
required-features = []

[features]
default = ["dotenv"]
dotenv = ["dep-dotenv"]

[dependencies]
caolo-sim = { git = "https://github.com/caolo-game/cao-sim.git", features=[] }
cao-lang = { git = "https://github.com/caolo-game/cao-lang.git" }
caolo-messages = { path= "../messages" }

log = "*"
env_logger = "*"
chrono = { version="0.4", features=["serde"] }
serde_json = "1"
serde_yaml = "0.8"
serde = "1"
serde_derive = "1"
redis = "0.15"
rand="*"
sentry = "0.12"
rmp-serde = "0.14"

dep-dotenv = { version="0.14", optional=true, package="dotenv" }
uuid = { version="0.7" }

[dev-dependencies]
env_logger = { version="*", default-features=false }
