[package]
name = "caolo-worker"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"
build="build.rs"

[[bin]]
name = "caolo-worker"
required-features = ["with-serde"]

[build-dependencies]
protoc-rust = { version="2" }

[features]
default = ["dotenv", "with-serde"]
dotenv = ["dep-dotenv"]
with-serde = [] # for protobuf

[dependencies]
caolo-sim = { path = "../simulation", features=[] }
cao-lang = { git = "https://github.com/caolo-game/cao-lang.git" }

log = "*"
env_logger = "*"
chrono = { version="0.4", features=["serde"] }
serde_json = "1"
serde_yaml = "0.8"
serde = "1"
serde_derive = "1"
redis = "0.15"
rand="*"

dep-dotenv = { version="0.14", optional=true, package="dotenv" }
uuid = { version="0.7" }
protobuf = { version="2", features=["with-serde"] }
