name: Queen

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test suite

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri

      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler -y
          protoc --version

      - name: Install test-all-features
        run: cargo install cargo-all-features

      - name: Check all features
        run: |
          cargo check-all-features
        working-directory: sim

      - name: Run tests
        run: |
          make test
        working-directory: sim
        env:
          RUST_LOG: caolo_sim=trace
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 0
          RUSTDOCFLAGS: "-Cpanic=abort"

  clippy_check:
    runs-on: ubuntu-latest
    name: Clippy check
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler -y
          protoc --version

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ./sim/Cargo.toml
