name: Rust

on: [push]

jobs:
  build:
    name: Build and test worker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: build
      run: cargo build
      
    - name: run tests
      run: cargo test
