[package]
name = "caolo-web"
version = "0.1.0"
authors = ["Daniel Kiss <littlesnorrboy@gmail.com>"]
edition = "2018"

[[bin]]
name = "caolo-web"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["web-dotenv"]
web-dotenv = ["dotenv"]

[dependencies]
dotenv = { version="0.9", optional=true }
reqwest = { version= "0.10", features = ["json"] }

actix = "0.9"
actix-web = "2"
actix-identity = "0.2"
actix-cors = "0.2"
actix-rt = "1"
# actix-web-actors = "2"
oauth2 = "1.3"
log = "0.4"
failure = "0.1"
serde = { version = "1", features=["derive"] }
serde_json = "1"
env_logger = "0.7"
